# Generated by Django 4.1.3 on 2024-04-27 04:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('index_number', models.IntegerField(max_length=8)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('opt_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('location', models.CharField(max_length=150)),
                ('luggage_number', models.IntegerField()),
                ('booking_code', models.CharField(max_length=50, unique=True)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
