# Generated by Django 4.2.11 on 2024-04-30 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_booking_index_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='index_number',
            new_name='amount',
        ),
    ]
